### ISSUE TITLE
floating issues multipleOf

### ISSUE THREAD

**Issue by JochemBlok** [thephpleague/json-guard#102]
With the following property in the schema

"dekking": {
    "type": "number",
    "multipleOf": 0.01,
    "minimum": -99999999.99,
    "maximum": 99999999.99
}

And with a value of 2.34 the validator is complaining. 

Replacing the two lines so we use the BCMatch module solves the problem.

So in file League\JsonGuard\Constraints\MultipleOf

$quotient = $value / $multiple;
$mod      = $quotient - floor($quotient);

The lines must be replaced by:

$quotient = bcdiv($value, $multiple, 9);
$mod      = bcsub($quotient, $quotient, 9);

**Comment by yuloh** [comment]
If we fix this with bcmath we need to make that a required dependency.  I was considering making bcmath required already since you need it for comparisons to be 100% accurate anyway.

**Comment by JochemBlok** [comment]
Thanks for your reply! For now I solved is with a custom RuleSet with my own implementation of the MultipleOf constraint.

**Comment by yuloh** [comment]
I just tagged 1.0.0-alpha which includes this fix. I'm going to close this issue but feel free to re-open it if you encounter this issue again.
