### ISSUE TITLE
Making the ErrorCode class an interface instead

### ISSUE THREAD

**Issue by nyamsprod** [thephpleague/json-guard#11]
https://github.com/thephpleague/json-guard/blob/master/src/ErrorCode.php#L5

Okay this is me nitpicking. But I think it would be better to make this class an Interface as constants define in an interface [can not be overwritten by classes that extend them](http://php.net/manual/en/language.oop5.interfaces.php#language.oop5.interfaces.constants).

**Comment by yuloh** [comment]
That's a good point, I hadn't considered that.  It feels weird making it an interface, because it isn't meant to be implemented.  It isn't meant to be extended either, so maybe it should be marked as final?

**Comment by nyamsprod** [comment]
Yes after thinking about it. I suppose a final class would also be a good idea. Interfaces imply a contract. These are final values that should won't change. So a final class would also prevent accidental value changes. So a final class is fine by me :+1:

**Comment by yuloh** [comment]
Thanks for reading through the code and the feedback, I really appreciate it 😄 

Closed by e4ad321bae796d9b4bb31ab3da7cf147cf52f6e8
