### ISSUE TITLE
CVV validation

### ISSUE THREAD

**Issue by MarcoVigna17** [thephpleague/json-guard#136]
Hey all 👋 

I used this json-guard package in one of my recent project, where I had to define a custom rule to validate a cvv number (the Credit Card Validation code).

I think it would be handy to have it in the main package as it could be often used.

I've opened a PR (https://github.com/thephpleague/json-guard/pull/135) to introduce it, feel free to accept it or not!

**Comment by yuloh** [comment]
Hi Marco,

I replied to the pull request.  Let me know if you have any questions.

Thanks,

Matt
