### ISSUE TITLE
Required constraint fails with null data

### ISSUE THREAD

**Issue by ivoba** [thephpleague/json-guard#19]
I get this error:

> get_object_vars() expects parameter 1 to be object, null given
> vendor/league/json-guard/src/Constraints/Required.php:25

Im not sure what the according json element is that causes this, at the moment, but maybe you already have an idea.

**Comment by yuloh** [comment]
Hi, 

Thanks for catching this. We use the official [JSON Schema Test Suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite), which is missing a test case for this.  The required constraint should ignore non objects.

I going to open a PR against the test suite to catch this, and add a fix to the required constraint.

**Comment by ivoba** [comment]
wow that was fast, thx :+1:
