### ISSUE TITLE
get_object_vars() expects parameter 1 to be object, array given

### ISSUE THREAD

**Issue by HeathNaylor** [thephpleague/json-guard#22]
Error
```
A PHP Error was encountered

Severity: Warning

Message: get_object_vars() expects parameter 1 to be object, array given

Filename: Constraints/Required.php

Line Number: 15
```

JSON to decode
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "type": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "type"
  ],
  "additionalProperties": false
}
```

Decoded PHP object
```
{#48
  +"$schema": "http://json-schema.org/draft-04/schema#"
  +"type": "object"
  +"properties": {#55
    +"id": {#56
      +"type": "string"
    }
    +"type": {#57
      +"type": "string"
    }
  }
  +"required": array:2 [
    0 => "id"
    1 => "type"
  ]
  +"additionalProperties": false
}
```

Code
```
$dereferencer = new Dereferencer();
$schema= json_decode($jsonString);
$schema= $dereferencer->dereference($schema);
$validator = new Validator($jsonDecodedUserInput, $schema);
```

**Comment by yuloh** [comment]
Hello,

Thanks for the detailed report 👍

This looks like the same error in #19 that was fixed by #20.

If you use the master branch it should work correctly.  I will tag a new release soon.  Feel free to reopen this issue if your issue isn't fixed on master.

**Comment by HeathNaylor** [comment]
@yuloh pulled from HEAD of master, now I get this when I call `$validator->errors()`

```
array:1 [
  0 => ValidationError {#61
    -message: "Value "<ARRAY>" is not a(n) object."
    -code: 28
    -pointer: ""
    -value: array:2 [
      "id" => 500000001
      "type" => 0
    ]
    -constraints: []
  }
]
```

**Comment by yuloh** [comment]
That looks like a legitimate validation error, because the user data is an array and you specified `"type": "object"` in your schema.

**Comment by HeathNaylor** [comment]
The above error was for the `Type` constraint being `object`.

I changed `Required.php` to be the following:
```
<?php

namespace League\JsonGuard\Constraints;

use League\JsonGuard\ErrorCode;
use League\JsonGuard\ValidationError;

class Required implements PropertyConstraint
{
    /**
     * {@inheritdoc}
     */
    public static function validate($data, $parameter, $pointer = null)
    {
        if (!is_array($data)) {
            return null;
        }

        $actualProperties = array_keys($data);
        $missing          = array_diff($parameter, $actualProperties);
        if (count($missing)) {
            return new ValidationError(
                'Required properties missing.',
                ErrorCode::MISSING_REQUIRED,
                $data,
                $pointer,
                ['required' => $parameter]
            );
        }

        return null;
    }
}
``` 

Basically ensuring that the `$data` passed in MUST be an array and getting rid of `get_object_vars()`. I will fork and do a PR tomorrow at some point, but there may need to be a greater discussion around this?

**Comment by yuloh** [comment]
The required constraint is only supposed to apply when `$data` is an object.  If you changed it than [this test](https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/develop/tests/draft4/required.json#L23) from the official test suite would fail.

Do you mean a check to make sure that the required property in the schema is an array?

**Comment by HeathNaylor** [comment]
Eh, ignore me, didn't realize the data passed to JsonGuard had to be an object. Working now.
