### ISSUE TITLE
Custom RuleSet are not passed on when creating instances of 'Validator' for sub-schemas

### ISSUE THREAD

**Issue by labbati** [thephpleague/json-guard#29]
When we create a new `Validator`, we can provide our own set of rules through constructor parameter `$ruleSet`.
When validators for sub-schemas are created through `makeSubSchemaValidator` the same set of rules are NOT passed on to the constructor. This causes sub-schemas to always use `DraftFour` instead of our custom set of rule.

What I propose is to add the argument `$ruleSet` to the call to `Validator::__construct` in `makeSubSchemaValidator` with value `$this->ruleSet`.

**Comment by yuloh** [comment]
Hello,

This should be  fixed by #25.  If you pull from master it should work correctly.  I will tag a new release shortly.

> What I propose is to add the argument $ruleSet to the call to Validator::__construct in makeSubSchemaValidator with value $this->ruleSet.

That makes way more sense then how I fixed it; I forgot that was a constructor parameter 😬

**Comment by labbati** [comment]
Correct me if I am wrong, but looks like that #25 fixes forwarding of custom extension for `format` rule (e.g. `date-time`) and the way you fixed it looks absolutely perfect to me.
On the other hand, what I am proposing is to fix the forwarding of the entire set of rules, an object implementing the `RuleSet` interface to be clear.
In particular I need to write a custom rule `myRule` that would sit at the same level of `required`.

```
type: object
properties: [....]
required: ['prop1', 'prop2']
myRule: [...]
^^^^^^
```

**Comment by yuloh** [comment]
Hey @labbati,

Sorry, I edited the comment once I realized.  Your fix should work perfect. I opened #30 with your fix but it looks like travis got stuck.

**Comment by labbati** [comment]
Hey @yuloh thanks for being o responsive and for fixing this issue so quicky! Looking forward to having it included in a release soon :smile:.

**Comment by yuloh** [comment]
Hey @labbati, I just tagged 0.3.2 which should fix your issue.  Feel free to reopen this if you are still having problems.

**Comment by labbati** [comment]
Thanks! Currently using 0.3.2! It works perfectly :smiley:
