### ISSUE TITLE
Dereferencer: circular external references aren't turned into Reference objects

### ISSUE THREAD

**Issue by stuartherbert** [thephpleague/json-guard#50]
This is a contrived example, but it does illustrate the issue :)

Given the following schema, as `watch-list.v1.json`:

```
{
    "$schema": "http://json-schema.org/schema#",
    "id": "http://example.com/schemas/etl/watch-list.v1.json",
    "type": "array",
    "items": [
        { "$ref": "watch-for.v1.json" }
    ],
    "minItems": 1
}
```

and the following schema, as `watch-for.v1.json`:

```
{
    "$schema": "http://json-schema.org/schema#",
    "id": "http://example.com/schemas/etl/watch-for.v1.json",
    "type": "array",
    "items": [
        { "$ref": "watch-list.v1.json" }
    ],
    "minItems": 1
}
```

... when I run this code (after disabling the call to `getResolvedResolutionScope()` in `Dereferencer::makeReferenceAbsolute()`, so that relative file references will resolve):

```
$dereferencer = new Dereferencer;
$schema = $dereferencer->dereference("file://" . realpath(__DIR__ . '/../public/schemas/json-guard-bugs/circular-external-references/watch-list.v1.json'));
```

... the Dereferencer runs in an endless loop until PHP segfaults.

Looking through the Dereferencer, I can't see any code to turn external references into Reference objects (a la the documentation). `Dereferencer::crawl()` only appears to turn internal references into Reference objects.

**Comment by yuloh** [comment]
Good catch, the external references are not lazily resolved.

I pushed a WIP branch to fix this here:

https://github.com/thephpleague/json-guard/compare/master...yuloh:lazy-external-refs?expand=1

If you want to try it out, give it a shot.  I will clean it up and get it ready to merge when I get a chance.
