### ISSUE TITLE
External referencing via $ref is not working

### ISSUE THREAD

**Issue by rodnover55** [thephpleague/json-guard#83]
Hello. I have issue with external loading scheme.

I have two schemas:

Company:
```
{
    "id": "http://example.com/company",
    "properties": {
        "id": { "type": "integer" },
        "name": { "type": "string" }
    },
    "required": ["id", "name"],
    "type": "object"
}
```
Client:
```
{
    "id": "http://example.com/client",
    "definitions": {
        "company": {
            "$ref": "http://example.com/company"
        }
    },
    "type": "object",
    "properties": {
        "name": { "type": "string" },
        "phone": { "type": "string" },
        "company": { "$ref": "#/definitions/company" }
    },
    "required": ["name", "phone", "company"]
}
```

Validation object with `http://example.com/client` is completed without errors, but `company.id` is required .

```
{
    "name": "Test",
    "phone": "some-phone",
    "company": {
        "name": "Mildberry"
    }
}
```

As I see it happens because field with type `\League\JsonGuard\Reference` is not resolved [here](https://github.com/thephpleague/json-guard/blob/master/src/Dereferencer.php#L200) and [here](https://github.com/thephpleague/json-guard/blob/master/src/Dereferencer.php#L181).

**Comment by yuloh** [comment]
Thanks for fixing this!  I'm going to close the issue.  Please reopen it if you are still running into issues.
