### ISSUE TITLE
Custom invalid/required error messages

### ISSUE THREAD

**Issue by atompulse** [thephpleague/json-guard#86]
Hi there!

I wonder if there's any chance to get custom invalid/required error messages ?

I use in our projects on the client side http://bugventure.github.io/jsen/errors and it provides an awesome and simple way of adding custom messages in the schema definition like:
http://bugventure.github.io/jsen/errors

```
var schema = {
        type: 'object',
        properties: {
            username: {
                type: 'string',
                minLength: 5,
                invalidMessage: 'Invalid username',
                requiredMessage: 'Username is required'
            }
        },
        required: ['username']
    };
```
I explored the code in this packages and noticed that every error is raised using the ValidationError class which receives an error message;
I wonder if it would be possible to use the $pointer to actually get a custom error message from the schema definition ?

**Comment by yuloh** [comment]
Hello,

The simplest way to use custom error messages is to look them up based on the `keyword`.  As an example, I am using [this language file](https://github.com/yuloh/illuminate-json-guard/blob/master/resources/lang/en/validation.php) to translate messages for Laravel [like this](https://github.com/yuloh/illuminate-json-guard/blob/master/src/ErrorMessageTranslator.php).

In your example the  `invalidMessage` applies to the entire schema, not a specific keyword.  There isn't really a way to do that using the library itself at the moment.

> I wonder if it would be possible to use the $pointer to actually get a custom error message from the schema definition ?

The error pointer is pointing to the value that caused the error, not the schema.  For your example the pointer will be `/username` but you are going to need `/properties/username` to figure out what the error message is.

The validator doesn't keep a pointer to where it is in the schema so there isn't really an easy way to pass that along to the error ATM.

**Comment by yuloh** [comment]
I think the best solution to this that is still generally useful is to pass the schema and/or the schema pointer back in the error message.

**Comment by atompulse** [comment]
Hi @yuloh ,
I spent some considerable time trying to achieve what you suggested 
> to pass the schema and/or the schema pointer back in the error message
but unfortunately is not possible to do it without completely redesigning the whole code.
I believe the code quality in this lib is far superior than any other php json schema validator that I had analyzed (and trust me I analyzed more than a dozen) but the design just doesn't considers this error customization aspect.
Also the default values (coercion) is another aspect that seems to be of great value and again its not possible at the moment from what I come to understand.
But I believe given enough effort this can be achieved - the issue is that at this moment I don't have the time to perform this.

As a solution I found https://github.com/geraintluff/jsv4-php which is a semi-abandoned/not maintained package but which has a very simple design and I was able to completely refactor it and add custom error message features to it and also have default values; I use your schema Dereferencer (which is freaking awesome) to handle the dereferencing aspects.

I understand its not the perfect solution but I have to be pragmatic.

Thank you for your time and thoughts.

Cheers!

**Comment by yuloh** [comment]
Hey @atompulse,

I'm refactoring how the constraints work in #88.  Once that is merged it should be possible to change the error signature to include a schema pointer and the schema.

> Also the default values (coercion) is another aspect that seems to be of great value and again its not possible at the moment from what I come to understand.

I _think_ you could do this by writing a custom ruleset that decorates every constraint and sets the default before calling the constraint.  This should be a lot easier once #88 is merged.  I will try and write a gist when I get a chance.  You could probably do type coercion too this way.

> As a solution I found https://github.com/geraintluff/jsv4-php which is a semi-abandoned/not maintained package but which has a very simple design and I was able to completely refactor it and add custom error message features to it and also have default values; I use your schema Dereferencer (which is freaking awesome) to handle the dereferencing aspects.

Nice!  Glad the dereferencer worked for that library too.  I will probably split the dereferencer into it's own library if it proves to be useful for other projects.

I'm going to keep this open until we add schema info to the error object.

**Comment by atompulse** [comment]
@yuloh sounds good!
The changes in [#88](https://github.com/thephpleague/json-guard/pull/88) seems to circumvent current design issues and will open the lib for new possibilities. Nice work!

Related to the dereferencer I'm 100% confident that it could become the defacto php dereferencer for json schema if you give the merits it deserves by publishing it as an independent library :1st_place_medal: 

Cheers!

**Comment by yuloh** [comment]
Hello 👋 

I just tagged `1.0.0-alpha`, which includes a pointer to the schema as well as the schema itself, so it should be pretty straightforward to get the custom message from the schema.

1.0 rule sets are also easier to extend, so implementing a custom validator that sets defaults should be easier.

I'm going to close this issue but feel free to re-open it if you have any questions.
