### ISSUE TITLE
Value { .. } is not a(n) "object"

### ISSUE THREAD

**Issue by northern** [thephpleague/json-guard#89]
Hi there,

I'm started using this library and I'm running into a bit of snag. I receive the following error:

    Value {"firstName":"John","lastName":"Doe","age":82} is not a(n) "object"

I'm using an example schema from this page:

http://json-schema.org/examples.html

And I'm validating against this document:
```javascript
{
  "firstName":"John",
  "lastName":"Doe",
  "age":82
}
```
Which I assume, according to the schema should validate.

When I remove the `type` attribute from the schema (under the `title`) the validation does seem to pass (at least, it isn't throwing errors) but if I remove the `firstName` attribute from the document (which, according to the schema is required) the document also seems to validate.

I'm obviously doing something wrong, however, I can't seem to figure out what.

Any help much appreciated.
Thanks

**Comment by yuloh** [comment]
Hi,

Are you json decoding the data before passing it to the validator?  If you passed the data as a string that would happen.

**Comment by northern** [comment]
Hi,

I figured out the problem. Totally my bad. I was using `json_decode($json, true)` on my data. I always prefer to work with arrays instead of objects.

Which actually, coming to think of it, might be a bit of an issue for me. It means that I will have to decode my incoming data twice, once as an object for JSON validation and a second time before it's used elsewhere.

Anyhow, thanks for the quick response!

**Comment by yuloh** [comment]
Oh, that makes sense.  The validator can't work with arrays because some schemas become impossible to validate (see [FAQ](http://json-guard.thephpleague.com/faq/)).  I should probably put a note in getting started too, drive
